#52 add Requests for DayFullOverview, DayCompactOverview, AverageWork…
Stier-09/hwr_zeiterfassung pull request #59
Opened 2022-04-05 22:20 UTC by Stier-09

…ingHours and AveragePause in Interval

2022-04-06 09:10 UTC, valientes commented on src/main/java/com/hwr/hwrzeiterfassung/controller/OverviewController.java
> +    Iterable<DayOverviewFull> getDayFullOverviewsInInterval(@RequestParam String email, @RequestParam String password, @RequestParam LocalDate start, @RequestParam LocalDate end) {
Geht das mit LocalDate ohne Konvertieren? Ich bin da gerade ein wenig am verzweifeln, weil ich immer einen Bad Request zurückbekomme, `Parse attempt failed for value [2022-03-01]` (ich gebe das ohne Klammern an)

2022-04-06 11:17 UTC, TomxHWRxWI20C approved these changes

2022-04-07 13:33 UTC, valientes requested changes

2022-04-07 13:33 UTC, valientes commented on src/main/java/com/hwr/hwrzeiterfassung/controller/OverviewController.java
> +    @GetMapping(path = "/AveragePauseInInterval")
Diese Methode hat `InInterval` im Namen drin, allerdings gibt der User kein Zeitintervall an, stattdessen sind die letzten 10 Tage hardgecoded. Absicht?

2022-04-07 18:11 UTC, Stier-09 commented on src/main/java/com/hwr/hwrzeiterfassung/controller/OverviewController.java
> +    @GetMapping(path = "/AveragePauseInInterval")
übersehen vom Testing

2022-04-07 18:16 UTC, valientes approved these changes

2022-04-07 18:16 UTC, merged