70 backlog update human informations
Stier-09/hwr_zeiterfassung pull request #71
Opened 2022-04-08 09:00 UTC by Stier-09

2022-04-08 11:29 UTC, valientes requested changes

2022-04-08 11:29 UTC, valientes commented on src/main/java/com/hwr/hwrzeiterfassung/controller/UpdateController.java
> +    HttpStatus changeName(@RequestParam String email, @RequestParam String password, @RequestParam double targetDailyWorkingTime) {
Copy-Paste-Fehler beim Namen der Funktion?

2022-04-08 11:29 UTC, valientes commented on src/main/java/com/hwr/hwrzeiterfassung/controller/UpdateController.java
> +    HttpStatus changeName(@RequestParam String email, @RequestParam String password, @RequestParam int projectId) {
Copy-Paste-Fehler beim Namen der Funktion?

2022-04-08 13:28 UTC, Stier-09 commented on src/main/java/com/hwr/hwrzeiterfassung/controller/UpdateController.java
> +    HttpStatus changeName(@RequestParam String email, @RequestParam String password, @RequestParam double targetDailyWorkingTime) {
jup

2022-04-08 13:29 UTC, Stier-09 commented on src/main/java/com/hwr/hwrzeiterfassung/controller/UpdateController.java
> +    HttpStatus changeName(@RequestParam String email, @RequestParam String password, @RequestParam int projectId) {
jup

2022-04-08 13:32 UTC, valientes approved these changes

2022-04-11 07:06 UTC, TomxHWRxWI20C approved these changes

2022-04-11 07:11 UTC, merged