#67 Unittests database repository
Stier-09/hwr_zeiterfassung pull request #81
Opened 2022-04-12 19:33 UTC by valientes

Also test setup.
Closes #67

2022-04-12 20:27 UTC, Stier-09 requested changes
Am Ende der Dateien bitte immer eine leere Zeile

2022-04-12 20:27 UTC, Stier-09 commented on pom.xml
> +            <version>4.12</version>
hier wäre glaube die Version besser:
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>5.4.0</version>
        <scope>test</scope>
    </dependency>

2022-04-13 14:14 UTC, Stier-09 approved these changes

2022-04-14 10:01 UTC, TomxHWRxWI20C approved these changes

2022-04-14 10:02 UTC, merged