72-backlog-update-day-times
Stier-09/hwr_zeiterfassung pull request #82
Opened 2022-04-12 21:58 UTC by Stier-09

2022-04-13 17:17 UTC, valientes requested changes

2022-04-13 17:17 UTC, valientes commented on src/main/java/com/hwr/hwrzeiterfassung/controller/CorrectTimeController.java
> +    public Optional<DayAndListOfTimes> getDayInformationAndTimes(@RequestParam String email, @RequestParam String password, @RequestParam LocalDate date) {
Ich glaube, wir brauchen da wieder ein `@DateTimeFormat` für `date`

2022-04-14 09:44 UTC, TomxHWRxWI20C approved these changes

2022-04-14 13:26 UTC, valientes approved these changes

2022-04-14 14:47 UTC, merged