Draft: Setup für Controller-Tests
Stier-09/hwr_zeiterfassung pull request #85
Opened 2022-04-14 17:13 UTC by valientes

@Stier-09 kannst du mal bitte reinschauen, ob dir die Configuration des Tests so passt? Dann übernehme ich das auch für die anderen Tests

2022-04-15 23:28 UTC, Stier-09 requested changes
es wäre gut, wenn die Funktionen mit mehreren Tests und auch Tests für die Randfälle abgedeckt werden

2022-04-20 17:56 UTC, Stier-09 requested changes
sieht gut aus, nur bitte darauf achten, dass nur ein assert pro test verwendet wird

2022-04-29 06:58 UTC, valientes commented
Ich muss die bestehenden Tests noch an das Refactoring anpassen (gerade beim DayController wurde was entfernt, wodurch der build nicht funktioniert

2022-05-02 07:13 UTC, Stier-09 approved these changes
bitte Commits noch zusammenfassen

2022-05-03 15:00 UTC, TomxHWRxWI20C approved these changes

2022-05-03 16:02 UTC, nicoregenberg approved these changes

2022-05-03 18:34 UTC, merged